### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by hrshtmlng** [bytemakers/Become-A-Member#15]
### Name

Harshit Malang

**Comment by hrshtmlng** [comment]
Few links are broken in readme

**Comment by devarshishimpi** [comment]
Welcome @hrshtmlng 👋🏻 Hope you have a great time here!
I have invited you. Do check your email for the invitation. And don't forget to check out the rest of our socials at https://bio.link/bytemakers

**Comment by devarshishimpi** [comment]
> Few links are broken in readme

Thanks for reporting. Will fix the same!
