### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by pritamrajput** [bytemakers/Become-A-Member#16]
### Name

Pritam Chauhan

**Comment by devarshishimpi** [comment]
Welcome @priyankarpal 👋🏻 Hope you have a great time here!
I have invited you. Do check your email for the invitation. And don't forget to check out the rest of our socials at https://bio.link/bytemakers

**Comment by pritamrajput** [comment]
Yes I have checked my mail. I have joined the organization. Thank you for accepting my request

**Comment by devarshishimpi** [comment]
Great! 🙌🏻 I hope you have a great stay here!
