### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by dushmanta05** [bytemakers/Become-A-Member#19]
### Name

Dushmanta

**Comment by dushmanta05** [comment]
Hi, I don't know why I received this error run, any help? 
![20230131_003155](https://user-images.githubusercontent.com/73304098/215570412-ce925011-2977-430a-b75a-1accd9b92fe8.png)

**Comment by devarshishimpi** [comment]
> Hi, I don't know why I received this error run, any help?
> 
> ![20230131_003155](https://user-images.githubusercontent.com/73304098/215570412-ce925011-2977-430a-b75a-1accd9b92fe8.png)

Hi, Actually the Github Action has to be reconfigured.

**Comment by devarshishimpi** [comment]
> ### Name
> Dushmanta

Welcome @dushmanta05  👋🏻 Hope you have a great time here!
I have invited you. Do check your email for the invitation. And don't forget to check out the rest of our socials at https://bio.link/bytemakers

**Comment by dushmanta05** [comment]
Thank you, I've accepted the invitation, glad to join you guys :)

**Comment by devarshishimpi** [comment]
Always! Hope you have a great stay here 😄
