### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by zaidahmad25** [bytemakers/Become-A-Member#29]
### Name

Zaid Ahmad

**Comment by devarshishimpi** [comment]
Welcome @zaidahmad25  👋🏻 Hope you have a great time here!
I have invited you. Do check your email for the invitation. And don't forget to check out the rest of our socials at https://bio.link/bytemakers

**Comment by zaidahmad25** [comment]
Thank you!
