### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Bharadwajshivam28** [bytemakers/Become-A-Member#40]
### Name

Shivam Kumar

**Comment by devarshishimpi** [comment]
Welcome @Bharadwajshivam28  👋🏻 Hope you have a great time here!
I have invited you. Do check your email for the invitation. And don't forget to check out the rest of our socials at https://bio.link/bytemakers

**Comment by Bharadwajshivam28** [comment]
> Welcome @Bharadwajshivam28  👋🏻 Hope you have a great time here!
> I have invited you. Do check your email for the invitation. And don't forget to check out the rest of our socials at https://bio.link/bytemakers

Thanks 👍 sure I will check all
